tasks:
  jfrog-build:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package
           ls -a
    - docker/build:
         image: razoropsrepocode/spring
         #image: razoropscode.jfrog.io/docker/spring
         push: true 
         tags: ["latest-v1"] 
