 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sample-java-app
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: java-app
   template:
     metadata:
       labels:
         app: java-app
     spec:
       containers:
       - name: java-app
         image: razoropsrepocode/spring:latest-v2 #us.icr.io/plasmadonar/plasma:v1
         imagePullPolicy: Always
         ports:
         - containerPort: 8080
